apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: smartpay-db
build:
  artifacts:
    - image: gcr.io/charliebertvg/smartpay/smartpay-db
      context: .
      docker:
        dockerfile: docker/Dockerfile
deploy:
  kustomize:
    paths:
      - kubernetes/overlays/dev
profiles:
- name: prod
  build:
    artifacts:
    - image: gcr.io/charliebertvg/smartpay/smartpay-db
      context: .
      docker:
        dockerfile: docker/Dockerfile.prod
  deploy:
    kustomize:
      paths:
        - kubernetes/overlays/prod
        #portforward debug
portForward:
  - resourceType: service
    resourceName: smartpay-db
    port: 8002
    localPort: 8002
