services:
  smartpay-db-api:
    image: smartpay-db-api
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8002
    volumes:
      - ../:/usr/src/app/
    ports:
      - 8002:8002
      - 10001:10001
    environment:
      - DEBUGGER=True
      - WEB_APP_VERSION=0.1.0
      - WEP_APP_TITLE=smartpay-db
      - WEP_APP_DESCRIPTION=Database service for SmartPay
      - ENVIRONMENT=dev
      - POSTGRES_DATABASE_URL=postgres://postgres:postgres@smartpay-db:5432/smartpay_dev_db
      - DEFAULT_DATA=False
    networks:
      - smartpay
    depends_on:
      smartpay-db:
        condition: service_healthy

  smartpay-db:
    image: smartpay-db
    build:
      context: ../db
      dockerfile: Dockerfile
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smartpay_dev_db
    volumes:
      - smartpay-db:/var/lib/postgresql/data
    networks:
      - smartpay
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 10

volumes:
  smartpay-db:
    external: true

networks:
  smartpay:
    external: true
