apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartpay-db
spec:
  selector:
    matchLabels:
      app: smartpay-db
  replicas: 1
  template:
    metadata:
      labels:
        app: smartpay-db
    spec:
      containers:
      - name: smartpay-db
        image: gcr.io/charliebertvg/smartpay/smartpay-db
        ports:
        - containerPort: 8002
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health-check
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health-check
            port: 8002
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: smartpay-db
          valueFrom:
            configMapKeyRef:
              name: smartpay-db-secret
              key: ENVIRONMENT
        - name: WEB_APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: smartpay-db-secret
              key: WEB_APP_VERSION
